# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'Utils.xcworkspace'


targetsArray = ['tableView']
for index in 0..targetsArray.length - 1 do
    proj = targetsArray[index]
    target proj do
        # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
        use_frameworks!
        project proj + '/' + proj + '/' +proj + '.xcodeproj'
        # Pods for TestA
       pod 'SnapKit', '~> 4.0.0'
       
    end
end

